# Generated by Django 3.1.7 on 2021-06-16 07:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('level', models.IntegerField(default=0)),
                ('describe', models.CharField(default='', max_length=100)),
                ('create_user', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update_user', models.IntegerField(default=0)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('state', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('level', models.IntegerField(default=0)),
                ('describe', models.CharField(default='', max_length=100)),
                ('create_user', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update_user', models.IntegerField(default=0)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('state', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=10)),
                ('passwd', models.CharField(default='123456', max_length=20)),
                ('sex', models.CharField(max_length=2)),
                ('bossnumber', models.IntegerField(default=0)),
                ('bossname', models.CharField(max_length=10)),
                ('entry_time', models.DateField()),
                ('create_user', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update_user', models.IntegerField(default=0)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('state', models.IntegerField(default=1)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organization.department')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organization.position')),
            ],
        ),
    ]
