# Generated by Django 3.1.7 on 2021-06-29 06:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pid', models.IntegerField(default=-1)),
                ('describe', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Matter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pid', models.IntegerField(default=-1)),
                ('describe', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(default='', max_length=25)),
                ('state', models.CharField(default='', max_length=25)),
                ('begin_time', models.DateField(default='2000-01-01')),
                ('delivery_time', models.DateField(default='2000-01-01')),
                ('state_description', models.CharField(default='', max_length=256)),
                ('project_description', models.CharField(default='', max_length=256)),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=10)),
                ('passwd', models.CharField(default='123456', max_length=20)),
                ('sex', models.CharField(max_length=2)),
                ('bossnumber', models.IntegerField(default=0)),
                ('bossname', models.CharField(max_length=10)),
                ('entry_time', models.DateField()),
                ('phone', models.IntegerField(default=0)),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organization.department')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organization.position')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=5)),
                ('progress', models.FloatField(max_length=5)),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organization.matter')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organization.project')),
                ('staff', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Organization.staff')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
                ('project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Organization.project')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organization.staff')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='director',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='staff_director', to='Organization.staff'),
        ),
        migrations.AddField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='staff_manager', to='Organization.staff'),
        ),
        migrations.AddField(
            model_name='project',
            name='matter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Organization.matter'),
        ),
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('time', models.FloatField(max_length=5)),
                ('progress', models.FloatField(max_length=5)),
                ('content', models.CharField(max_length=256)),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organization.matter')),
                ('project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Organization.project')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organization.staff')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organization.task')),
            ],
        ),
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('weight', models.IntegerField(default=0)),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organization.project')),
                ('rater_20', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_rater_20', to='Organization.staff')),
                ('rater_30', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_rater_30', to='Organization.staff')),
                ('rater_50', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_rater_50', to='Organization.staff')),
            ],
        ),
    ]
