# Generated by Django 3.1.7 on 2021-06-16 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='department',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='department',
            name='last_update_date',
        ),
        migrations.RemoveField(
            model_name='department',
            name='last_update_user',
        ),
        migrations.RemoveField(
            model_name='department',
            name='state',
        ),
        migrations.RemoveField(
            model_name='position',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='position',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='position',
            name='last_update_date',
        ),
        migrations.RemoveField(
            model_name='position',
            name='last_update_user',
        ),
        migrations.RemoveField(
            model_name='position',
            name='state',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='last_update_date',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='last_update_user',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='state',
        ),
    ]
