# Generated by Django 3.1.7 on 2021-06-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='bossnumber',
            new_name='boss_id',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='bossname',
            new_name='boss_name',
        ),
    ]
