# Generated by Django 3.1.7 on 2021-06-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0003_auto_20210629_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
