# Generated by Django 3.1.7 on 2021-06-29 07:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0005_auto_20210629_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期'),
        ),
        migrations.AddField(
            model_name='score',
            name='date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='score',
            name='mod_date',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改日期'),
        ),
        migrations.AddField(
            model_name='score',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Organization.project'),
        ),
        migrations.AddField(
            model_name='score',
            name='project_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='rater',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Organization.staff'),
        ),
        migrations.AddField(
            model_name='score',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='score_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Achievements',
        ),
    ]
