# Generated by Django 3.1.7 on 2021-06-29 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0006_auto_20210629_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Organization.staff'),
        ),
        migrations.AlterField(
            model_name='score',
            name='rater',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='staff_rater', to='Organization.staff'),
        ),
    ]
