# Generated by Django 3.1.7 on 2021-07-05 15:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0007_auto_20210629_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('weight', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
                ('rater', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ScoreMember_rater', to='Organization.staff')),
                ('staff', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Organization.staff')),
            ],
        ),
    ]
